### ISSUE TITLE
Url encode namespaces

### ISSUE THREAD

**Issue by StanislavGoryachev** [openwhisk/openwhisk-client-swift#1]
When trying to invoke an action for a namespace containing a space for example "My Company", an error 400 is returned. 

Instead one must do "My%20Company" which works, but is't pretty.

Maybe all string should be url encoded, including packages and actions?

**Comment by rabbah** [comment]
Indeed, namespaces and package, and entity names must be encoded.

**Comment by paulcastro** [comment]
Yes, this should have been done.  I made changes and created a PR for this.  I can just merge myself if no one objects.

**Comment by paulcastro** [comment]
I merged the changes into 0.1.2.
