### ISSUE TITLE
Xcode 8 and Swift 3 support?

### ISSUE THREAD

**Issue by rmey** [openwhisk/openwhisk-client-swift#25]
Hello,
is there any plan to update the lib to Swift 3.0 and Xcode 8?

**Comment by paulcastro** [comment]
Hi yes, we have a swift 3 branch I was keeping up to date up until beta 6.  Let me make sure it works with the Xcode 8 release.

**Comment by paulcastro** [comment]
I updated and merged the Swift 3 updates into master PR #26
