### ISSUE TITLE
Readme has wrong git url for instructions on using swift package manager

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-client-swift#5]
https://github.com/openwhisk/openwhisk-client-swift#swift-package-manager

```
dependencies: [
    .Package(url:  "https://github.com/openwhisk/swift-client-sdk.git", versions: Version(0,0,0)..<Version(1,0,0)),
  ]
```

It should be https://github.com/openwhisk/openwhisk-client-swift.git

**Comment by jberstler** [comment]
I believe this will be resolved with #4 is merged.

**Comment by csantanapr** [comment]
Thank you sir for your prompt response to my issue :-)

**Comment by paulcastro** [comment]
Merged
