### ISSUE TITLE
Add audio library support for mobile.

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/openwhisk-client-swift#6]
Some possible Whisk use cases may require audio sources. We should create a generic library that allows audio capture and streaming to help in the creation of these use cases. 

cc @paulcastro 

blue_#1180

**Comment by paulcastro** [comment]
What extensions to standard libraries would this provide?  AVRecorder may be enough.

Perhaps one value add would be to check that the audio file is within whatever limits we are enforcing.

**Comment by csantanapr** [comment]
@paulcastro I don't know, you tell me what this should provide since you are the originator of the idea :-)

**Comment by dgrove-oss** [comment]
Closing issue as project is being archived.
